import type {Metadata} from 'next';
import {IBM_Plex_Serif} from 'next/font/google';
import './globals.css';

const mainFont = IBM_Plex_Serif({weight: '300', subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Web & Mobile Application Engineer | Frank Lakatos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className}>{children}</body>
    </html>
  );
}
